name: Deploy AFE Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      command:
        description: 'Select the command to run'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Set environment variables based on input
        id: set_env_vars
        run: |

          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "TARGET_GROUP_ARN=arn:aws:elasticloadbalancing:us-east-1:867089037134:targetgroup/afe-prod/d86c3fb58d495135" >> $GITHUB_ENV
            echo "EC2_INSTANCE_NAME=afe-prod" >> $GITHUB_ENV
          else
            echo "TARGET_GROUP_ARN=arn:aws:elasticloadbalancing:us-east-1:867089037134:targetgroup/afe-dev/00f1f0044374f784" >> $GITHUB_ENV
            echo "EC2_INSTANCE_NAME=afe-dev" >> $GITHUB_ENV
          fi

          echo $TARGET_GROUP_ARN
          echo $EC2_INSTANCE_NAME

      - name: Checkout
        uses: actions/checkout@v4